# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='body_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='body_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='body_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='body_5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='body_6',
            field=models.TextField(blank=True),
        ),
    ]
