# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171113_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='murals',
            new_name='mural',
        ),
    ]
