# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171114_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mural',
            old_name='picture',
            new_name='mural_picture',
        ),
    ]
