# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171114_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mural',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='Slug',
            new_name='slug',
        ),
    ]
