# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171114_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='heroes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
